apiVersion: v1
kind: Service
metadata:
  name: as-fields-api-service
  labels:
    app: as-fields-api
spec:
  selector:
    app: as-fields-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
