apiVersion: apps/v1
kind: Deployment
metadata:
  name: as-fields-api
  labels:
    app: as-fields-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: as-fields-api
  template:
    metadata:
      labels:
        app: as-fields-api
    spec:
      containers:
        - name: as-fields-api
          image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/as-fields-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: AWS_REGION
              value: "${AWS_REGION}"
            - name: AWS_DEFAULT_REGION
              value: "${AWS_REGION}"
          envFrom:
            - secretRef:
                name: aws-credentials
            - configMapRef:
                name: as-fields-config
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "512Mi"
