apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: as-fields-api
  namespace: default
  labels:
    release: stable
spec:
  namespaceSelector:
    matchNames:
       - default
  selector:
    matchLabels:
      app: as-fields-api
  endpoints:
  - port: tcp
    path: /metrics
    interval: 10s